// this class generated by class com.p6spy.engine.common.Subclasser

package com.p6spy.engine.subclass;

import com.p6spy.engine.spy.*;
import java.sql.*;
import javax.sql.*;
import oracle.jdbc.pool.*;


public class P6OracleOCIConnectionPool extends oracle.jdbc.pool.OracleOCIConnectionPool {

  public P6OracleOCIConnectionPool (java.lang.String p0, java.lang.String p1, java.lang.String p2) throws java.sql.SQLException {
    super( p0,  p1,  p2);
  }
  public P6OracleOCIConnectionPool () throws java.sql.SQLException {
    super();
  }
  public P6OracleOCIConnectionPool (java.lang.String p0, java.lang.String p1, java.lang.String p2, java.util.Properties p3) throws java.sql.SQLException {
    super( p0,  p1,  p2,  p3);
  }
  public Connection getConnection() throws SQLException {
    return P6SpyDriverCore.wrapConnection(super.getConnection());
  };

  public Connection getConnection(String username, String password) throws SQLException {
    return P6SpyDriverCore.wrapConnection(super.getConnection(username, password));
  };

}
