// this class generated by class com.p6spy.engine.common.Subclasser

package com.p6spy.engine.subclass;

import com.p6spy.engine.spy.*;
import java.sql.*;
import javax.sql.*;
import com.p6spy.engine.spy.*;


public class P6P6DataSource extends com.p6spy.engine.spy.P6DataSource {

  public P6P6DataSource (javax.sql.DataSource p0) {
    super( p0);
  }
  public P6P6DataSource () {
    super();
  }
  public Connection getConnection() throws SQLException {
    return P6SpyDriverCore.wrapConnection(super.getConnection());
  };

  public Connection getConnection(String username, String password) throws SQLException {
    return P6SpyDriverCore.wrapConnection(super.getConnection(username, password));
  };

}
