
package com.p6spy.engine.wrapper;

/**
 * Marker interface added to all proxies generated by P6Spy.  Any object which implements this interface
 * can be considered to be a proxy created by P6Spy.
 */
public interface P6Proxy {

  /**
   * Returns the underlying object for the proxy.
   * <p>
   * WARNING: This is an internal method for P6Spy.  This method should not be called directly.  Use the methods
   * on the {@link java.sql.Wrapper} interface instead!
   * @return the underlying object being proxied
   */
  Object unwrapP6SpyProxy();
}
